### ISSUE TITLE
Staging Checklist - Verify FE is working as expected

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#228]
### DoD:
- [x] User can lock ocean, extend amount, extend lock, extend amount + lock
- [x] User can allocate voting power across assets
- [x] User can allocate across many assets in 1 transaction
- [x] User is able to see enough data to make an informed decision as how to lock
- [x] User is able to see how much time is left and how many rewards they have accumulated
- [x] User can claim all rewards
- [x] User can withdraw locked ocean from VE. (test w/ short period). This is tested in df-py, have not tested in df-web.

**Comment by idiom-bytes** [comment]
We've managed to continue improving testing on ganache, manipulating the chain, and verifying its working e2e.

There might be some bugs here and there, but we have done this enough to validate the basics are in place and are able to easily reproduce the necessary conditions.

**Comment by idiom-bytes** [comment]
We've managed to continue improving testing on ganache, manipulating the chain, and verifying its working e2e.

There might be some bugs here and there, but we have done this enough to validate the basics are in place and are able to easily reproduce the necessary conditions.
