### ISSUE TITLE
Ship veDelegation

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/df-web#472]
### Problem:
Users have to delegate to other wallets and use basic features

### Solution:
End User are able to use a component that delegates their voting power to a separate address (Contract). 

### DoD:
- [x] All tasks associated are completed
- [x] E2E tests are completed
- [x] Ensure docs are updated for delegation. Action: Roberto sync w Ana; then make docs happen as needed
