### ISSUE TITLE
[Cand B] webapp runs dftool locally every 10 min -> csvs -> local DB

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/df-web#48]
**Overview**

Aim of issue: support ["Cand B" Data Flow](https://docs.google.com/presentation/d/11Nu_emSgw3iYZKDcmnvZC_aOM00MDyYTtTWQP4PYox4/edit#slide=id.gf3ff445a1c_0_286) "webapp runs dftool locally every 10 min -> csvs -> local DB" will follow this. 

Note: this follows ["Cand 0" Data Flow](https://docs.google.com/presentation/d/11Nu_emSgw3iYZKDcmnvZC_aOM00MDyYTtTWQP4PYox4/edit#slide=id.gf3ff445a1c_0_75) "webapp consumes weekly-created csvs". It's in [df-web#52](https://github.com/oceanprotocol/df-web/issues/52). If we wanted to skip that and jump straight to _this_ issue (48), that's fine:)

**TODOs**
- [x] Build: Run dftool locally, generate csvs - @trizin waiting for https://github.com/oceanprotocol/df-py/pull/80 #76
- [x] Build: Grab csvs and put into DB. - [df-sql](https://github.com/oceanprotocol/dfpy-sql-backend)
- [x] Build: render DB into table in webapp @KatunaNorbert 
- [x] Build: auto-run the above things every 10 min (or whatever interval makes sense)
  - [x] [df-sql](https://github.com/oceanprotocol/dfpy-sql-backend) parses csvs every 10 mins
  - [x] #76
