### ISSUE TITLE
Start tracking events in Plausible Analytics

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/df-web#486]
Dependant on: https://github.com/oceanprotocol/team-sailfish/issues/21

Since we decided that we can move forward with Plausible, we should set up the events in df-web. 

Steps:

- [ ] Decide which events to track
- [ ] Decide the user journeys that we want to follow
- [ ] Add the tracking tags within the frontend 
- [ ] All basic end-to-end funnels have been setup and delivered

**Comment by jamiehewitt15** [comment]
Duplicated by: https://github.com/oceanprotocol/df-web/issues/489

**Comment by jamiehewitt15** [comment]
So I'd suggest that to start with, we track these user journeys: 
- Locking Ocean
- Allocating Ocean
