### ISSUE TITLE
[APY calc v2] Include Fees inside the Lock OCEAN component

### ISSUE THREAD

**Issue by KatunaNorbert** [oceanprotocol/df-web#677]
### Background / motivation

When some users engage in Passive DF by locking OCEAN to get passive rewards, by the time they've got some rewards they often feel blindsided by the tx fees. Often to the point where they've lost $. (Esp if they've locked a small amount of OCEAN for a short time.)

These issues led to [this Slack discussion](https://oceanprotocol.slack.com/archives/C026BNFH6HK/p1700493696589089) from Nov 21, 2023. One outcome of _that_ discussion is the TODOs of this issue.

### Detailed specs

Also in the slack discussion, we ([got specs](https://oceanprotocol.slack.com/archives/C026BNFH6HK/p1700562766020829?thread_ts=1700493696.589089&cid=C026BNFH6HK):

Ultimately the user wants to know: **How much $ do I stand to net, and what is my APY?** (Where APY accounts for costs.) Let's give them a practical tool.

The "$ to net" / "APY" values are based on:

1. current tentative values for # OCEAN to lock and lock time (or ones already committeD)
2. tx costs based on realistic estimates of tx costs including realistic counts of # txs needed eg in a given claim session
3. how often the user would compound (which incurs more tx fees). This is critical, for reasons mentioned above in this comment.

I am imagining a widget where the user can see these values.

- For (1) those are set in the main part of passive-df screen.
- For (2) it needs eth gas station with the option of a user-set gas cost; and it needs to realistically estimate the # times a tx is needed (even I don't have great insight into that, so I feel for the poor user).
- For (3) the user could specify how frequently. Ideally there's a special button to auto-compute this (using optimization, as mentioned a few msgs above).

For gas usage estimates: we run some simulated txs, count the gas used, and then take the max # observed.

### TODO

Inside the Lock OCEAN component add information about the tx fees costs in the following way:
- [x] calculate and display tx fees costs for the basic actions: lock, claim, withdraw
- [x] for the claim txs cost, calculate what is the min number of claims the user has to do( lock period / 52 weeks )
- [x] calculate and display the cost of compounding based on a number of compounds input
- [x] display the final expected rewards amount including the tx fees costs
- [x] add a component for turning on/off optimal compounding calculation #681
- [x] add function that calculates the most optimal lock configuration #682
- [ ] update APY calculation to include fees #683
- [x] modal UI updates #684
- [x] add component that displays compound details #692
